version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/python_learning_platform
      - CODE_SANDBOX_URL=http://code-sandbox:5001
    depends_on:
      - db
      - code-sandbox
    volumes:
      - ./backend:/app
    networks:
      - app-network
    # Hardware limitations 
    mem_limit: 300m
    cpus: 0.5
    memswap_limit: 400m
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite 
    depends_on:
      - backend
    networks:
      - app-network
    # Hardware limitations for frontend
    mem_limit: 400m
    cpus: 0.5
    memswap_limit: 500m
    restart: unless-stopped

  code-sandbox:
    build: ./code-sandbox
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./code-sandbox:/app
    networks:
      - app-network
    # Add security 
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    # Hardware limitations for sandbox (more restrictive for security)
    mem_limit: 200m
    cpus: 0.25
    memswap_limit: 250m
    restart: unless-stopped

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=python_learning_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # Hardware limitations for database
    mem_limit: 512m
    cpus: 0.75
    memswap_limit: 600m
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4:8.1
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 8080:80
  #   networks:
  #     - app-network
  #   # Resource limits for pgadmin (optional)
  #   # Uncomment if needed:
  #   # mem_limit: 100m
  #   # cpus: 0.25

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 