-- Drop tables with CASCADE
DROP TABLE IF EXISTS CONTENIDO CASCADE;
DROP TABLE IF EXISTS CURSO CASCADE;
DROP TABLE IF EXISTS EJEMPLOS CASCADE;
DROP TABLE IF EXISTS EVALUACION CASCADE;
DROP TABLE IF EXISTS MODULO CASCADE;
DROP TABLE IF EXISTS NOTA CASCADE;
DROP TABLE IF EXISTS PROBLEMA CASCADE;
DROP TABLE IF EXISTS PROGRESo+   O CASCADE;
DROP TABLE IF EXISTS ROL CASCADE;
DROP TABLE IF EXISTS SECCION CASCADE;
DROP TABLE IF EXISTS SUBSECCION CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS USUARIO_CURSO CASCADE;

-- Create tables
CREATE TABLE CURSO (
   COD_CURSO SERIAL PRIMARY KEY,
   TITULO_CURSO VARCHAR(50) NOT NULL,
   DESCRIPCION_CURSO TEXT,
   IMAGEN_CURSO BYTEA
);

CREATE TABLE MODULO (
   COD_MODULO SERIAL PRIMARY KEY,
   COD_CURSO INT NOT NULL,
   TITULO_MODULO VARCHAR(256) NOT NULL,
   DESCRIPCION_MODULO TEXT,
   FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO)
);

CREATE TABLE SECCION (
   COD_MODULO INT NOT NULL,
   COD_SECCION SERIAL NOT NULL,
   TITULO_SECCION VARCHAR(256) NOT NULL,
   DESCRIPCION_SECCION TEXT,
   PRIMARY KEY (COD_MODULO, COD_SECCION),
   FOREIGN KEY (COD_MODULO) REFERENCES MODULO (COD_MODULO)
);

CREATE TABLE SUBSECCION (
   COD_MODULO INT NOT NULL,
   COD_SECCION INT NOT NULL,
   COD_SUBSECCION SERIAL NOT NULL,
   TITULO_SUBSECCION VARCHAR(256) NOT NULL,
   DESCRIPCION_SUBSECCION TEXT,
   PRIMARY KEY (COD_MODULO, COD_SECCION, COD_SUBSECCION),
   FOREIGN KEY (COD_MODULO, COD_SECCION) REFERENCES SECCION (COD_MODULO, COD_SECCION)
);

CREATE TABLE CONTENIDO (
   COD_MODULO INT NOT NULL,
   COD_SECCION INT NOT NULL,
   COD_SUBSECCION INT NOT NULL,
   COD_CONTENIDO SERIAL NOT NULL,
   IMAGEN BYTEA,
   DESCRIPCION TEXT,
   LINK VARCHAR(500),
   PRIMARY KEY (COD_MODULO, COD_SECCION, COD_SUBSECCION, COD_CONTENIDO),
   FOREIGN KEY (COD_MODULO, COD_SECCION, COD_SUBSECCION) REFERENCES SUBSECCION (COD_MODULO, COD_SECCION, COD_SUBSECCION)
);

CREATE TABLE EVALUACION (
   COD_EVALUACION SERIAL PRIMARY KEY,
   COD_MODULO INT,
   COD_SECCION INT,
   FOREIGN KEY (COD_MODULO, COD_SECCION) REFERENCES SECCION (COD_MODULO, COD_SECCION)
);

CREATE TABLE PROBLEMA (
   COD_PROBLEMA SERIAL PRIMARY KEY,
   COD_EVALUACION INT,
   COD_MODULO INT,
   COD_SECCION INT,
   COD_SUBSECCION INT,
   TITULO_PROBLEMA VARCHAR(100) NOT NULL,
   DESCRIPCION_PROBLEMA TEXT NOT NULL,
   INPUT TEXT NOT NULL,
   OUTPUT TEXT NOT NULL,
   FOREIGN KEY (COD_EVALUACION) REFERENCES EVALUACION (COD_EVALUACION),
   FOREIGN KEY (COD_MODULO, COD_SECCION, COD_SUBSECCION) REFERENCES SUBSECCION (COD_MODULO, COD_SECCION, COD_SUBSECCION)
);

CREATE TABLE EJEMPLOS (
   COD_PROBLEMA INT NOT NULL,
   COD_EJEMPLO SERIAL NOT NULL,
   INPUT_EJEMPLO TEXT NOT NULL,
   OUTPUT_EJEMPLO TEXT NOT NULL,
   PRIMARY KEY (COD_PROBLEMA, COD_EJEMPLO),
   FOREIGN KEY (COD_PROBLEMA) REFERENCES PROBLEMA (COD_PROBLEMA)
);

CREATE TABLE ROL (
   COD_ROL SERIAL PRIMARY KEY,
   ROL VARCHAR(30) NOT NULL
);

CREATE TABLE USUARIO (
   COD_USUARIO SERIAL PRIMARY KEY,
   COD_ROL INT NOT NULL,
   NOMBRE VARCHAR(256) NOT NULL,
   USUARIO VARCHAR(20) NOT NULL,
   PASSWORD VARCHAR(256) NOT NULL,
   EMAIL VARCHAR(256) NOT NULL,
   FOREIGN KEY (COD_ROL) REFERENCES ROL (COD_ROL)
);

CREATE TABLE USUARIO_CURSO (
   COD_CURSO INT NOT NULL,
   COD_USUARIO INT NOT NULL,
   PRIMARY KEY (COD_CURSO, COD_USUARIO),
   FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
   FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
);

CREATE TABLE NOTA (
   COD_PROBLEMA INT NOT NULL,
   COD_USUARIO INT NOT NULL,
   NOTA NUMERIC NOT NULL,
   NOTA_TOTAL NUMERIC NOT NULL,
   PRIMARY KEY (COD_PROBLEMA, COD_USUARIO),
   FOREIGN KEY (COD_PROBLEMA) REFERENCES PROBLEMA (COD_PROBLEMA),
   FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
);

CREATE TABLE PROGRESO (
   COD_CURSO INT NOT NULL,
   COD_USUARIO INT NOT NULL,
   COD_MODULO INT NOT NULL,
   COD_SECCION INT NOT NULL,
   TOTAL INT NOT NULL,
   TOTAL_TERMINADO INT NOT NULL,
   PRIMARY KEY (COD_CURSO, COD_USUARIO, COD_MODULO, COD_SECCION),
   FOREIGN KEY (COD_CURSO, COD_USUARIO) REFERENCES USUARIO_CURSO (COD_CURSO, COD_USUARIO),
   FOREIGN KEY (COD_MODULO, COD_SECCION) REFERENCES SECCION (COD_MODULO, COD_SECCION)
);






-- SI YA CREARON LA BD SIN IMAGENES:
ALTER TABLE CURSO
ADD COLUMN IMAGEN_CURSO BYTEA;


ALTER TABLE CONTENIDO
ALTER COLUMN IMAGEN TYPE BYTEA
USING decode(IMAGEN, 'base64');
