name: Back Tests

on:
  pull_request:
    branches: ['sprint-*']

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: python_learning_platform
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      working-directory: ./backend
      env:
        FLASK_APP: app.py
        FLASK_ENV: testing
        DATABASE_URL: postgresql://user:password@localhost:5432/python_learning_platform
        SECRET_KEY: your-secret-key-here
        JWT_SECRET_KEY: your-jwt-secret-key-here
      run: |
        pytest --cov=app tests/